name: Ansible CI

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install ansible ansible-lint yamllint checkov

      - name: YAML lint
        run: yamllint .

      - name: Ansible syntax check
        run: |
           for file in $(grep -rl "hosts:" . --include="*.yml" --include="*.yaml"); do
               echo "Checking playbook $file"
               ansible-playbook "$file" --syntax-check || exit 1
           done
      - name: Ansible lint
        run: ansible-lint .

      - name: Security scan
        run: checkov -d .
